name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs -y
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://vamshikrishna89:$HF_TOKEN@huggingface.co/spaces/vamshikrishna89/test hf-space

          rsync -av --exclude ".git" \
                    --exclude ".github" \
                    --exclude "__pycache__" \
                    --exclude "*.pyc" \
                    ./ hf-space/

          cd hf-space

          cat > README.md <<EOF
          ---
          title: MoneyPrinterTurbo
          emoji: 🚀
          colorFrom: blue
          colorTo: purple
          sdk: docker
          pinned: false
          license: mit
          ---

          # MoneyPrinterTurbo
          EOF

          git add .
          git commit
          git push
